/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 21 23:08:50 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.StringWriter;
import java.nio.BufferOverflowException;
import java.nio.CharBuffer;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.IllegalFormatConversionException;
import java.util.LinkedList;
import java.util.List;
import java.util.TreeSet;
import java.util.UnknownFormatConversionException;
import java.util.Vector;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HelpAppendable_ESTest extends HelpAppendable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendTitle((CharSequence) null);
      assertEquals(1, TextHelpAppendable.DEFAULT_LEFT_PAD);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      Vector<String> vector0 = new Vector<String>();
      HashSet<List<String>> hashSet0 = new HashSet<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("(suWV>X>Rwh5qOFX", linkedList0, vector0, hashSet0);
      textHelpAppendable0.appendTable(tableDefinition0);
      assertEquals(7, TextHelpAppendable.DEFAULT_LIST_INDENT);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      char[] charArray0 = new char[5];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      textHelpAppendable0.appendList(false, (Collection<CharSequence>) null);
      assertEquals(7, TextHelpAppendable.DEFAULT_LIST_INDENT);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(1);
      textHelpAppendable0.appendHeader(95, charBuffer0);
      assertEquals(0, charBuffer0.arrayOffset());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      textHelpAppendable0.appendParagraph("");
      assertEquals(3, TextHelpAppendable.DEFAULT_INDENT);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[2];
      textHelpAppendable0.appendParagraphFormat("", objectArray0);
      assertEquals(3, textHelpAppendable0.getIndent());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      char[] charArray0 = new char[5];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTitle(charBuffer0);
        fail("Expecting exception: BufferOverflowException");
      
      } catch(BufferOverflowException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.CharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable((TableDefinition) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Vector<TextStyle> vector0 = new Vector<TextStyle>();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("", vector0, linkedList0, (Iterable<List<String>>) null);
      textHelpAppendable0.setLeftPad((-495));
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      textHelpAppendable0.setMaxWidth(0);
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      LinkedList<String> linkedList1 = new LinkedList<String>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>();
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>(arrayDeque0);
      TableDefinition tableDefinition0 = TableDefinition.from("9:kN/du4M{eo:?GDJs", linkedList0, linkedList1, treeSet0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>(0);
      Vector<String> vector0 = new Vector<String>();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      arrayList0.add(textStyle0);
      TableDefinition tableDefinition0 = TableDefinition.from("w+4L5C]", arrayList0, vector0, (Iterable<List<String>>) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendTable(tableDefinition0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Array index out of range: 0
         //
         verifyException("java.util.Vector", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      textHelpAppendable0.resize(textStyle_Builder0, 525.944124878);
      Object[] objectArray0 = new Object[6];
      // Undeclared exception!
      textHelpAppendable0.appendParagraphFormat("c/nFuERPOv", objectArray0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[4];
      Object object0 = new Object();
      objectArray0[0] = object0;
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("Q<=,YF%GY:O", objectArray0);
        fail("Expecting exception: IllegalFormatConversionException");
      
      } catch(IllegalFormatConversionException e) {
         //
         // g != java.lang.Object
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[9];
      textHelpAppendable0.setIndent((-319));
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat("T", objectArray0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.Util", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextStyle.Builder textStyle_Builder0 = textHelpAppendable0.getTextStyleBuilder();
      Vector<CharSequence> vector0 = new Vector<CharSequence>();
      HashSet<String> hashSet0 = new HashSet<String>();
      hashSet0.add("S=_`DX2");
      vector0.addAll((Collection<? extends CharSequence>) hashSet0);
      textHelpAppendable0.resize(textStyle_Builder0, 0.0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendList(false, vector0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Width must be greater than 0
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendHeader(0, "@wE^A||");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // level must be at least 1
         //
         verifyException("org.apache.commons.cli.help.TextHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[5];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendFormat("!k_IE81PyY%Dp", objectArray0);
        fail("Expecting exception: UnknownFormatConversionException");
      
      } catch(UnknownFormatConversionException e) {
         //
         // Conversion = 'D'
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(stringWriter0);
      Object[] objectArray0 = new Object[6];
      objectArray0[0] = (Object) textHelpAppendable0;
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendFormat("Expected exactly one annotation to provide an ArgumentSource, found %d.", objectArray0);
        fail("Expecting exception: IllegalFormatConversionException");
      
      } catch(IllegalFormatConversionException e) {
         //
         // d != org.apache.commons.cli.help.TextHelpAppendable
         //
         verifyException("java.util.Formatter$FormatSpecifier", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      Object[] objectArray0 = new Object[0];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendFormat((String) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter(0);
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(stringBuffer0);
      Object[] objectArray0 = new Object[2];
      // Undeclared exception!
      try { 
        textHelpAppendable0.appendParagraphFormat((String) null, objectArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(stringWriter0);
      Object[] objectArray0 = new Object[6];
      textHelpAppendable0.appendFormat("Expected exactly one annotation to provide an ArgumentSource, found %d.", objectArray0);
      assertEquals(7, TextHelpAppendable.DEFAULT_LIST_INDENT);
  }
}
