/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 21 23:08:18 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import java.io.PipedWriter;
import java.io.StringWriter;
import java.nio.BufferOverflowException;
import java.nio.CharBuffer;
import java.nio.ReadOnlyBufferException;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FilterHelpAppendable_ESTest extends FilterHelpAppendable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) null, (-963), 29);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) "", 3, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      char[] charArray0 = new char[1];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) charBuffer0, (-3431), (-3431));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.HeapCharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      StringWriter stringWriter0 = new StringWriter();
      StringBuffer stringBuffer0 = stringWriter0.getBuffer();
      CharBuffer charBuffer0 = CharBuffer.wrap((CharSequence) stringBuffer0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append('\'');
        fail("Expecting exception: ReadOnlyBufferException");
      
      } catch(ReadOnlyBufferException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.StringCharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      char[] charArray0 = new char[8];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      textHelpAppendable0.append((CharSequence) charBuffer0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append('[');
        fail("Expecting exception: BufferOverflowException");
      
      } catch(BufferOverflowException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append('x');
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      PipedWriter pipedWriter0 = new PipedWriter();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(pipedWriter0);
      try { 
        textHelpAppendable0.append('|');
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      char[] charArray0 = new char[8];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      textHelpAppendable0.append('[');
      assertArrayEquals(new char[] {'[', '\u0000', '\u0000', '\u0000', '\u0000', '\u0000', '\u0000', '\u0000'}, charArray0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(74);
      TextHelpAppendable textHelpAppendable1 = (TextHelpAppendable)textHelpAppendable0.append((CharSequence) charBuffer0, 74, 74);
      assertEquals(3, textHelpAppendable1.getIndent());
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) "aEVI[O#];qR^?*v");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }
}
