/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 21 23:10:30 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.PriorityQueue;
import java.util.Set;
import java.util.Stack;
import java.util.Vector;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TableDefinition_ESTest extends TableDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      Vector<Locale.LanguageRange> vector0 = new Vector<Locale.LanguageRange>();
      Locale locale0 = Locale.PRC;
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) vector0, (Collection<String>) set0);
      TableDefinition tableDefinition0 = TableDefinition.from("", stack0, list0, (Iterable<List<String>>) null);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      Stack<List<String>> stack0 = new Stack<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("Bad URL key format [%s]; expected format is DocumentPath:Key.", arrayList0, (List<String>) null, stack0);
      List<String> list0 = tableDefinition0.headers();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>(arrayList0);
      Stack<String> stack0 = new Stack<String>();
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("", linkedList0, stack0, priorityQueue0);
      stack0.push("");
      List<String> list0 = tableDefinition0.headers();
      assertTrue(list0.contains(""));
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("org.apache.commons.cli.help.TableDefinition$1", (List<TextStyle>) null, (List<String>) null, linkedHashSet0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("", stack0, linkedList0, linkedHashSet0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Stack<TextStyle> stack0 = new Stack<TextStyle>();
      TextStyle textStyle0 = TextStyle.DEFAULT;
      stack0.add(textStyle0);
      Stack<List<String>> stack1 = new Stack<List<String>>();
      ArrayList<List<String>> arrayList0 = new ArrayList<List<String>>(stack1);
      TableDefinition tableDefinition0 = TableDefinition.from("org.apache.commons.text.lookup.JavaPlatformStringLookup", stack0, (List<String>) null, arrayList0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertTrue(list0.contains(textStyle0));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("$19+@RQ4tNr:", linkedList0, (List<String>) null, linkedHashSet0);
      String string0 = tableDefinition0.caption();
      assertEquals("$19+@RQ4tNr:", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>(arrayList0);
      Stack<String> stack0 = new Stack<String>();
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("", linkedList0, stack0, priorityQueue0);
      String string0 = tableDefinition0.caption();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      Stack<String> stack0 = new Stack<String>();
      LinkedList<List<String>> linkedList1 = new LinkedList<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, linkedList0, stack0, linkedList1);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNotNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      Stack<String> stack0 = new Stack<String>();
      LinkedList<List<String>> linkedList1 = new LinkedList<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, linkedList0, stack0, linkedList1);
      String string0 = tableDefinition0.caption();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      Stack<String> stack0 = new Stack<String>();
      LinkedList<List<String>> linkedList1 = new LinkedList<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, linkedList0, stack0, linkedList1);
      List<String> list0 = tableDefinition0.headers();
      assertTrue(list0.isEmpty());
  }
}
