/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 21 22:49:57 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.lang.reflect.Array;
import java.time.temporal.ChronoUnit;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Properties;
import java.util.function.Consumer;
import java.util.function.Supplier;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.OptionGroup;
import org.apache.commons.io.filefilter.IOFileFilter;
import org.apache.commons.text.TextStringBuilder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CommandLine_ESTest extends CommandLine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      commandLine_Builder0.setDeprecatedHandler((Consumer<Option>) null);
      CommandLine commandLine0 = commandLine_Builder0.get();
      assertNotNull(commandLine0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("options", "options");
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("B", "args", false, "directoryFilter");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      boolean boolean0 = commandLine0.hasOption("B");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option[] optionArray0 = new Option[4];
      Option[] optionArray1 = commandLine0.getParsedOptionValues(optionGroup0, optionArray0);
      assertSame(optionArray0, optionArray1);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option[] optionArray0 = commandLine0.getOptions();
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(optionArray0).when(supplier0).get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues(optionGroup0, supplier0);
      assertSame(optionArray0, objectArray0);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, false, ")P4\"nEoMu");
      Object[] objectArray0 = commandLine0.getParsedOptionValues(option0, (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      ChronoUnit[] chronoUnitArray0 = new ChronoUnit[0];
      ChronoUnit[] chronoUnitArray1 = commandLine0.getParsedOptionValues((Option) null, chronoUnitArray0);
      assertSame(chronoUnitArray0, chronoUnitArray1);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("0", "6", true, "0");
      Integer[] integerArray0 = new Integer[5];
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(integerArray0).when(supplier0).get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues(option0, supplier0);
      assertEquals(5, objectArray0.length);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("Vn", "Vn", false, "Vn");
      LinkedList<Option>[] linkedListArray0 = (LinkedList<Option>[]) Array.newInstance(LinkedList.class, 0);
      Supplier<LinkedList<Option>[]> supplier0 = (Supplier<LinkedList<Option>[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(linkedListArray0).when(supplier0).get();
      LinkedList<Option>[] linkedListArray1 = commandLine0.getParsedOptionValues(option0, supplier0);
      assertSame(linkedListArray0, linkedListArray1);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option[] optionArray0 = new Option[1];
      Option[] optionArray1 = commandLine0.getParsedOptionValues("org.apache.commons.cli.CommandLine$Builder", optionArray0);
      assertSame(optionArray0, optionArray1);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = new String[0];
      String[] stringArray1 = commandLine0.getParsedOptionValues("_a>$K*wD?U!-", stringArray0);
      assertSame(stringArray0, stringArray1);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Class<Option>[] classArray0 = (Class<Option>[]) Array.newInstance(Class.class, 6);
      Supplier<Class<Option>[]> supplier0 = (Supplier<Class<Option>[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(classArray0).when(supplier0).get();
      Class<Option>[] classArray1 = commandLine0.getParsedOptionValues("owChPtIZT", supplier0);
      assertSame(classArray1, classArray0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option[] optionArray0 = commandLine0.getOptions();
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(optionArray0).when(supplier0).get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues("org.apache.commons.cli.CommandLine", supplier0);
      assertEquals(0, objectArray0.length);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = new String[1];
      String[] stringArray1 = commandLine0.getParsedOptionValues('4', stringArray0);
      assertSame(stringArray0, stringArray1);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = IOFileFilter.EMPTY_STRING_ARRAY;
      Object[] objectArray0 = commandLine0.getParsedOptionValues('E', (Object[]) stringArray0);
      assertEquals(0, objectArray0.length);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<ChronoUnit[]> supplier0 = (Supplier<ChronoUnit[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      ChronoUnit[] chronoUnitArray0 = commandLine0.getParsedOptionValues('|', supplier0);
      assertNull(chronoUnitArray0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      ChronoUnit[] chronoUnitArray0 = new ChronoUnit[0];
      Supplier<ChronoUnit[]> supplier0 = (Supplier<ChronoUnit[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(chronoUnitArray0).when(supplier0).get();
      ChronoUnit[] chronoUnitArray1 = commandLine0.getParsedOptionValues('O', supplier0);
      assertSame(chronoUnitArray1, chronoUnitArray0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getParsedOptionValue((OptionGroup) null, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, "uS;0cI0gvoo6J]Fo/", true, "");
      String string0 = commandLine0.getParsedOptionValue(option0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<LinkedList<Integer>> supplier0 = (Supplier<LinkedList<Integer>>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      LinkedList<Integer> linkedList0 = commandLine0.getParsedOptionValue((String) null, supplier0);
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getParsedOptionValue("args", (Object) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Integer> supplier0 = (Supplier<Integer>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Integer integer0 = commandLine0.getParsedOptionValue('-', supplier0);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getParsedOptionValue('x', (Object) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, "=_T(Vz>GC;,-", true, (String) null);
      commandLine_Builder0.addOption(option0);
      Option[] optionArray0 = commandLine0.getOptions();
      assertEquals(1, optionArray0.length);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue((OptionGroup) null, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((CharSequence) null);
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue((OptionGroup) null, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue((OptionGroup) null, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue((Option) null, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("R");
      Option option0 = option_Builder0.get();
      char[] charArray0 = new char[1];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0);
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue((Option) null, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("H", "org.apache.commons.cli.CommandLine");
      String string0 = commandLine0.getOptionValue(option0, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("org.apache.commons.cli.HelpFormatter$Builder", (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder("");
      String string0 = commandLine0.getOptionValue("", (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue((String) null, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("", "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue('y', (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((-638));
      String string0 = commandLine0.getOptionValue('2', (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('L', (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('/', "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option((String) null, "");
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount(option0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("Z", "Z");
      commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount("Z");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      commandLine_Builder0.addArg("");
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getArgs();
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine_Builder0.addArg("FiQ`kMz");
      List<String> list0 = commandLine0.getArgList();
      assertTrue(list0.contains("FiQ`kMz"));
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue(optionGroup0, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, (String) null);
      Option.Builder option_Builder0 = Option.builder();
      try { 
        commandLine0.getParsedOptionValue(option0, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue("1>J4VSoP", (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue('v', (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option((String) null, true, "Akq0P");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      // Undeclared exception!
      try { 
        commandLine0.getOptionProperties((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption((Option) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String[] stringArray0 = new String[1];
      Supplier<String[]> supplier0 = (Supplier<String[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(supplier0).get();
      String[] stringArray1 = commandLine0.getParsedOptionValues(optionGroup0, supplier0);
      assertSame(stringArray0, stringArray1);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Integer[] integerArray0 = commandLine0.getParsedOptionValues((Option) null, supplier0);
      assertNull(integerArray0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      char[] charArray0 = new char[2];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0);
      String string0 = commandLine0.getParsedOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Integer> supplier0 = (Supplier<Integer>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Integer integer0 = commandLine0.getParsedOptionValue((OptionGroup) null, supplier0);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("B", "options");
      optionGroup0.setSelected(option0);
      ChronoUnit chronoUnit0 = ChronoUnit.NANOS;
      Supplier<ChronoUnit> supplier0 = (Supplier<ChronoUnit>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(chronoUnit0).when(supplier0).get();
      ChronoUnit chronoUnit1 = commandLine0.getParsedOptionValue(optionGroup0, supplier0);
      assertSame(chronoUnit1, chronoUnit0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine0.getParsedOptionValue((Option) null, (Supplier<ChronoUnit>) null);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getOptionValues((OptionGroup) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option.Builder option_Builder0 = Option.builder("iX18k");
      Option option0 = option_Builder0.get();
      optionGroup0.setSelected(option0);
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues((Option) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      String[] stringArray0 = commandLine0.getOptionValues(option0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((-4176));
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null);
      Class<Integer>[] classArray0 = (Class<Integer>[]) Array.newInstance(Class.class, 6);
      Class<Integer>[] classArray1 = commandLine0.getParsedOptionValues(option0, classArray0);
      assertSame(classArray1, classArray0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      int int0 = commandLine0.getOptionCount("?Q0]XXWV,96");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      LinkedList<String>[] linkedListArray0 = commandLine0.getParsedOptionValues(option0);
      assertNull(linkedListArray0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<LinkedList<Option>[]> supplier0 = (Supplier<LinkedList<Option>[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      LinkedList<Option>[] linkedListArray0 = commandLine0.getParsedOptionValues("", supplier0);
      assertNull(linkedListArray0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = commandLine0.getParsedOptionValues("", (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<Integer> linkedList0 = new LinkedList<Integer>();
      Supplier<LinkedList<Integer>> supplier0 = (Supplier<LinkedList<Integer>>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(linkedList0).when(supplier0).get();
      LinkedList<Integer> linkedList1 = commandLine0.getParsedOptionValue((String) null, supplier0);
      assertEquals(0, linkedList1.size());
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option[] optionArray0 = commandLine0.getParsedOptionValues("SF2ZhBty");
      assertNull(optionArray0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null, false, (String) null);
      Integer integer0 = commandLine0.getParsedOptionValue(option0);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder("N5+vL.=`s;vonpj+l");
      String string0 = commandLine0.getOptionValue("Bx|", (Supplier<String>) textStringBuilder0);
      assertEquals("N5+vL.=`s;vonpj+l", string0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getOptionObject("");
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption("File does not exist: ");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("owChPtIZT", false, "args");
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue(option0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, false, ")P4\"nEoMu");
      String string0 = commandLine0.getParsedOptionValue(option0, "Y/O7Adz1eXdz");
      assertEquals("Y/O7Adz1eXdz", string0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      LinkedList<Object> linkedList0 = commandLine0.getParsedOptionValue((String) null);
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("owChPtIZT", false, "args");
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine_Builder0.addOption(option0);
      Properties properties0 = commandLine0.getOptionProperties(option0);
      assertEquals(0, properties0.size());
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("Vn", "Vn", false, "Vn");
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption((OptionGroup) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("H", "org.apache.commons.cli.CommandLine");
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      Integer integer0 = commandLine0.getParsedOptionValue(optionGroup0);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("H", "org.apache.commons.cli.CommandLine");
      Supplier<Integer> supplier0 = (Supplier<Integer>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((-1)).when(supplier0).get();
      Integer integer0 = commandLine0.getParsedOptionValue(option0, supplier0);
      assertEquals((-1), (int)integer0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder("u&{%");
      String string0 = commandLine0.getOptionValue((OptionGroup) null, (Supplier<String>) textStringBuilder0);
      assertEquals("u&{%", string0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("H", "org.apache.commons.cli.CommandLine");
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      commandLine0.addOption(option0);
      String string0 = commandLine0.getOptionValue(optionGroup0, "[]");
      assertEquals("[]", string0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getParsedOptionValues((OptionGroup) null, (Supplier<String[]>) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option("H", "org.apache.commons.cli.CommandLine");
      commandLine0.addOption(option0);
      boolean boolean0 = commandLine0.hasOption(option0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine0.addOption((Option) null);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addArg("File does not exist: ");
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine0.addArg((String) null);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption((Option) null);
      assertSame(commandLine_Builder0, commandLine_Builder1);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addArg((String) null);
      assertSame(commandLine_Builder0, commandLine_Builder1);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getArgs();
      Object[] objectArray0 = commandLine0.getParsedOptionValues((OptionGroup) null, (Object[]) stringArray0);
      assertEquals(0, objectArray0.length);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      LinkedList<ChronoUnit> linkedList0 = new LinkedList<ChronoUnit>();
      LinkedList<ChronoUnit> linkedList1 = commandLine0.getParsedOptionValue((OptionGroup) null, linkedList0);
      assertSame(linkedList1, linkedList0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getOptionValues('L');
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue("Ht^9f9YSDWh^FS;<7", "Ht^9f9YSDWh^FS;<7");
      assertEquals("Ht^9f9YSDWh^FS;<7", string0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      List<String> list0 = commandLine0.getArgList();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue((Option) null, "g9%||}9 h");
      assertEquals("g9%||}9 h", string0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      boolean boolean0 = commandLine0.hasOption('$');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Object[] objectArray0 = commandLine0.getParsedOptionValues(optionGroup0, (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue('D');
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Properties properties0 = commandLine0.getOptionProperties((String) null);
      assertEquals(0, properties0.size());
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer[] integerArray0 = new Integer[5];
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(integerArray0).when(supplier0).get();
      Integer[] integerArray1 = commandLine0.getParsedOptionValues('=', supplier0);
      assertSame(integerArray0, integerArray1);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getOptionObject('H');
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      LinkedList<Option>[] linkedListArray0 = commandLine0.getParsedOptionValues('D');
      assertNull(linkedListArray0);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getOptionValues("org.apache.commons.text.CharacterPredicates");
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount('Q');
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Integer[] integerArray0 = commandLine0.getParsedOptionValues(optionGroup0);
      assertNull(integerArray0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((CharSequence) "org.apache.commons.text.CharacterPredicates");
      String string0 = commandLine0.getOptionValue('4', (Supplier<String>) textStringBuilder0);
      assertEquals("org.apache.commons.text.CharacterPredicates", string0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Class<String> class0 = String.class;
      Class<String> class1 = commandLine0.getParsedOptionValue('z', class0);
      assertFalse(class1.isPrimitive());
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('d', "true");
      assertEquals("true", string0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Iterator<Option> iterator0 = commandLine0.iterator();
      assertNotNull(iterator0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((CharSequence) "org.apache.commons.text.CharacterPredicates");
      String string0 = commandLine0.getParsedOptionValue('R', (Supplier<String>) textStringBuilder0);
      assertEquals("org.apache.commons.text.CharacterPredicates", string0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("Vn", "Vn", false, "Vn");
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues(optionGroup0, supplier0);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount((Option) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getParsedOptionValue("p", (Object) "p");
      assertEquals("p", object0);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      LinkedList<Option> linkedList0 = commandLine0.getParsedOptionValue('4');
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues('(', (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue((String) null);
      assertNull(string0);
  }
}
